//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coupons.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupons
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public long CompanyId { get; set; }
        public long Start_Date { get; set; }
        public long End_Date { get; set; }
        public int Amount { get; set; }
        public string Type { get; set; }
        public string Message { get; set; }
        public int Price { get; set; }
        public string Image { get; set; }
    }
}
