//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coupons.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CouponsEntities : DbContext
    {
        public CouponsEntities()
            : base("name=CouponsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<UserCoupons> UserCoupons { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Coupons> Coupons { get; set; }
        public virtual DbSet<AuthUsers> AuthUsers { get; set; }
    }
}
