//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coupons.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCoupons
    {
        public long UserId { get; set; }
        public long CouponId { get; set; }
    }
}
